// src/utils/emojiData.js

// {
//  char: "",
//  name: "",
//  keywords: ["", "", ""],
// }

export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    label: "Smileys",
    emojis: [
      {
        char: "😀",
        name: "Grinning Face",
        keywords: ["smile", "happy", "grin"],
      },
      {
        char: "😁",
        name: "Beaming Face with Smiling Eyes",
        keywords: ["smile", "happy", "grin"],
      },
      {
        char: "😂",
        name: "Face with Tears of Joy",
        keywords: ["laugh", "cry", "funny"],
      },
      {
        char: "🤣",
        name: "Rolling on the Floor Laughing",
        keywords: ["rofl", "laugh", "lol"],
      },
      {
        char: "😃",
        name: "Grinning Face with Big Eyes",
        keywords: ["smile", "happy", "joy"],
      },
      {
        char: "😄",
        name: "Grinning Face with Smiling Eyes",
        keywords: ["smile", "happy", "joy"],
      },
      {
        char: "😅",
        name: "Smiling Face with Sweat",
        keywords: ["relief", "sweat", "nervous"],
      },
      {
        char: "😆",
        name: "Grinning Squinting Face",
        keywords: ["laugh", "happy", "lol"],
      },
      { char: "😉", name: "Winking Face", keywords: ["flirt", "wink", "joke"] },
      {
        char: "😊",
        name: "Smiling Face with Smiling Eyes",
        keywords: ["happy", "smile", "blush"],
      },
      {
        char: "😋",
        name: "Face Savoring Food",
        keywords: ["yum", "delicious", "food"],
      },
      {
        char: "😎",
        name: "Smiling Face with Sunglasses",
        keywords: ["cool", "sunglasses", "chill"],
      },
      {
        char: "😍",
        name: "Smiling Face with Heart-Eyes",
        keywords: ["love", "heart", "crush"],
      },
      {
        char: "😘",
        name: "Face Blowing a Kiss",
        keywords: ["kiss", "love", "flirt"],
      },
      {
        char: "🥰",
        name: "Smiling Face with Hearts",
        keywords: ["love", "affection", "happy"],
      },
      { char: "😗", name: "Kissing Face", keywords: ["kiss", "love"] },
      {
        char: "😙",
        name: "Kissing Face with Smiling Eyes",
        keywords: ["kiss", "love"],
      },
      {
        char: "🥲",
        name: "Smiling Face with Tear",
        keywords: ["grateful", "emotional", "cry"],
      },
      {
        char: "😚",
        name: "Kissing Face with Closed Eyes",
        keywords: ["kiss", "love"],
      },
      { char: "☺️", name: "Smiling Face", keywords: ["happy", "smile"] },
      {
        char: "🙂",
        name: "Slightly Smiling Face",
        keywords: ["smile", "okay", "simple"],
      },
      {
        char: "🤗",
        name: "Smiling Face with Open Hands",
        keywords: ["hug", "happy", "support"],
      },
      {
        char: "🤩",
        name: "Star-Struck",
        keywords: ["excited", "star", "love"],
      },
      {
        char: "🤔",
        name: "Thinking Face",
        keywords: ["think", "hmm", "question"],
      },
      { char: "🫡", name: "Saluting Face", keywords: ["respect", "salute"] },
      {
        char: "🤨",
        name: "Face with Raised Eyebrow",
        keywords: ["skeptical", "doubt"],
      },
      { char: "😐", name: "Neutral Face", keywords: ["meh", "neutral"] },
      {
        char: "😑",
        name: "Expressionless Face",
        keywords: ["blank", "neutral"],
      },
      {
        char: "😶",
        name: "Face Without Mouth",
        keywords: ["silent", "mute", "speechless"],
      },
      {
        char: "🫥",
        name: "Dotted Line Face",
        keywords: ["invisible", "hidden"],
      },
      { char: "😶‍🌫️", name: "Face in Clouds", keywords: ["foggy", "unclear"] },
      {
        char: "🙄",
        name: "Face with Rolling Eyes",
        keywords: ["eyeroll", "annoyed"],
      },
      {
        char: "😏",
        name: "Smirking Face",
        keywords: ["smirk", "flirt", "sly"],
      },
      { char: "😣", name: "Persevering Face", keywords: ["struggle", "tired"] },
      {
        char: "😥",
        name: "Sad but Relieved Face",
        keywords: ["sad", "relief"],
      },
      {
        char: "😮",
        name: "Face with Open Mouth",
        keywords: ["surprised", "wow"],
      },
      {
        char: "🤐",
        name: "Zipper-Mouth Face",
        keywords: ["secret", "zip", "shut"],
      },
      { char: "😯", name: "Hushed Face", keywords: ["quiet", "surprised"] },
      { char: "😪", name: "Sleepy Face", keywords: ["tired", "sleep"] },
      { char: "😫", name: "Tired Face", keywords: ["exhausted", "tired"] },
      { char: "🥱", name: "Yawning Face", keywords: ["tired", "yawn"] },
      { char: "😴", name: "Sleeping Face", keywords: ["sleep", "zzz"] },
      { char: "😌", name: "Relieved Face", keywords: ["relaxed", "calm"] },
      { char: "😛", name: "Face with Tongue", keywords: ["tongue", "playful"] },
      {
        char: "😜",
        name: "Winking Face with Tongue",
        keywords: ["joke", "crazy", "wink"],
      },
      {
        char: "😝",
        name: "Squinting Face with Tongue",
        keywords: ["joke", "playful"],
      },
      { char: "🤤", name: "Drooling Face", keywords: ["hungry", "drool"] },
      { char: "😒", name: "Unamused Face", keywords: ["bored", "unimpressed"] },
      {
        char: "😓",
        name: "Downcast Face with Sweat",
        keywords: ["sad", "sweat"],
      },
      { char: "😔", name: "Pensive Face", keywords: ["sad", "thinking"] },
      { char: "😕", name: "Confused Face", keywords: ["confused", "unsure"] },
      {
        char: "🫤",
        name: "Face with Diagonal Mouth",
        keywords: ["unsure", "meh"],
      },
      { char: "🙃", name: "Upside-Down Face", keywords: ["silly", "flipped"] },
      { char: "🫠", name: "Melting Face", keywords: ["melt", "awkward"] },
      { char: "🤑", name: "Money-Mouth Face", keywords: ["rich", "money"] },
      { char: "😲", name: "Astonished Face", keywords: ["shocked", "wow"] },
      { char: "☹️", name: "Frowning Face", keywords: ["sad", "frown"] },
      {
        char: "🙁",
        name: "Slightly Frowning Face",
        keywords: ["sad", "upset"],
      },
      {
        char: "😖",
        name: "Confounded Face",
        keywords: ["frustrated", "confused"],
      },
      {
        char: "😞",
        name: "Disappointed Face",
        keywords: ["sad", "disappointed"],
      },
      { char: "😟", name: "Worried Face", keywords: ["worried", "concerned"] },
      {
        char: "😤",
        name: "Face with Steam From Nose",
        keywords: ["angry", "frustrated"],
      },
      { char: "😢", name: "Crying Face", keywords: ["sad", "cry"] },
      { char: "😭", name: "Loudly Crying Face", keywords: ["sad", "cry"] },
      {
        char: "😦",
        name: "Frowning Face with Open Mouth",
        keywords: ["sad", "shocked"],
      },
      {
        char: "😧",
        name: "Anguished Face",
        keywords: ["worried", "concerned"],
      },
      { char: "😨", name: "Fearful Face", keywords: ["scared", "fear"] },
      { char: "😩", name: "Weary Face", keywords: ["tired", "weary"] },
      { char: "🤯", name: "Exploding Head", keywords: ["mind blown", "shock"] },
      { char: "😬", name: "Grimacing Face", keywords: ["awkward", "nervous"] },
      { char: "😮‍💨", name: "Face Exhaling", keywords: ["relief", "exhale"] },
      {
        char: "😰",
        name: "Anxious Face with Sweat",
        keywords: ["worried", "sweat"],
      },
      {
        char: "😱",
        name: "Face Screaming in Fear",
        keywords: ["scared", "scream"],
      },
      { char: "🥵", name: "Hot Face", keywords: ["heat", "hot"] },
      { char: "🥶", name: "Cold Face", keywords: ["cold", "freeze"] },
      { char: "😳", name: "Flushed Face", keywords: ["embarrassed", "blush"] },
      { char: "🤪", name: "Zany Face", keywords: ["crazy", "wild"] },
      {
        char: "😵",
        name: "Face with Crossed-Out Eyes",
        keywords: ["dizzy", "dead"],
      },
      {
        char: "😵‍💫",
        name: "Face with Spiral Eyes",
        keywords: ["dizzy", "confused"],
      },
      { char: "🥴", name: "Woozy Face", keywords: ["drunk", "sick"] },
      { char: "😠", name: "Angry Face", keywords: ["angry", "mad"] },
      { char: "😡", name: "Pouting Face", keywords: ["angry", "furious"] },
      {
        char: "🤬",
        name: "Face with Symbols on Mouth",
        keywords: ["cursing", "angry"],
      },
      {
        char: "😷",
        name: "Face with Medical Mask",
        keywords: ["mask", "sick"],
      },
      { char: "🤒", name: "Face with Thermometer", keywords: ["sick", "ill"] },
      {
        char: "🤕",
        name: "Face with Head-Bandage",
        keywords: ["hurt", "injury"],
      },
      { char: "🤢", name: "Nauseated Face", keywords: ["sick", "vomit"] },
      { char: "🤮", name: "Face Vomiting", keywords: ["vomit", "sick"] },
      { char: "🤧", name: "Sneezing Face", keywords: ["sneeze", "sick"] },
      {
        char: "😇",
        name: "Smiling Face with Halo",
        keywords: ["angel", "innocent"],
      },
      { char: "🥳", name: "Partying Face", keywords: ["party", "celebration"] },
      { char: "🥸", name: "Disguised Face", keywords: ["disguise", "glasses"] },
      { char: "🥺", name: "Pleading Face", keywords: ["puppy eyes", "please"] },
      {
        char: "🥹",
        name: "Face Holding Back Tears",
        keywords: ["cry", "emotional"],
      },
      { char: "🤠", name: "Cowboy Hat Face", keywords: ["cowboy", "hat"] },
      { char: "🤡", name: "Clown Face", keywords: ["clown", "funny"] },
      { char: "🤥", name: "Lying Face", keywords: ["lie", "pinocchio"] },
      { char: "🫨", name: "Shaking Face", keywords: ["shake", "nervous"] },
      {
        char: "🙂‍↔️",
        name: "Head Shaking Horizontally",
        keywords: ["shake", "no"],
      },
      {
        char: "🙂‍↕️",
        name: "Head Shaking Vertically",
        keywords: ["shake", "yes"],
      },
      { char: "🤫", name: "Shushing Face", keywords: ["quiet", "shh"] },
      {
        char: "🤭",
        name: "Face with Hand Over Mouth",
        keywords: ["oops", "surprised"],
      },
      {
        char: "🫢",
        name: "Face with Open Eyes and Hand Over Mouth",
        keywords: ["shocked", "gasp"],
      },
      {
        char: "🫣",
        name: "Face with Peeking Eye",
        keywords: ["peeking", "shy"],
      },
      { char: "🧐", name: "Face with Monocle", keywords: ["inspect", "judge"] },
      { char: "🤓", name: "Nerd Face", keywords: ["nerd", "glasses"] },
      {
        char: "😈",
        name: "Smiling Face with Horns",
        keywords: ["devil", "evil"],
      },
      {
        char: "👿",
        name: "Angry Face with Horns",
        keywords: ["devil", "angry"],
      },
      { char: "👹", name: "Ogre", keywords: ["monster", "oni", "japan"] },
      { char: "👺", name: "Goblin", keywords: ["monster", "mask"] },
      { char: "💀", name: "Skull", keywords: ["death", "dead"] },
      {
        char: "☠️",
        name: "Skull and Crossbones",
        keywords: ["death", "danger"],
      },
      { char: "👻", name: "Ghost", keywords: ["spooky", "ghost", "boo"] },
      { char: "👽", name: "Alien", keywords: ["alien", "ufo"] },
      {
        char: "👾",
        name: "Alien Monster",
        keywords: ["monster", "video game"],
      },
      { char: "🤖", name: "Robot", keywords: ["robot", "bot"] },
      { char: "💩", name: "Pile of Poo", keywords: ["poop", "shit", "funny"] },
      { char: "😺", name: "Grinning Cat Face", keywords: ["cat", "smile"] },
      {
        char: "😸",
        name: "Grinning Cat Face with Smiling Eyes",
        keywords: ["cat", "happy"],
      },
      { char: "😹", name: "Cat with Tears of Joy", keywords: ["cat", "laugh"] },
      {
        char: "😻",
        name: "Smiling Cat with Heart-Eyes",
        keywords: ["cat", "love"],
      },
      { char: "😼", name: "Cat with Wry Smile", keywords: ["cat", "smirk"] },
      { char: "😽", name: "Kissing Cat", keywords: ["cat", "kiss"] },
      { char: "🙀", name: "Weary Cat", keywords: ["cat", "scared"] },
      { char: "😿", name: "Crying Cat", keywords: ["cat", "sad"] },
      { char: "😾", name: "Pouting Cat", keywords: ["cat", "angry"] },
      { char: "🙈", name: "See-No-Evil Monkey", keywords: ["monkey", "blind"] },
      {
        char: "🙉",
        name: "Hear-No-Evil Monkey",
        keywords: ["monkey", "ignore"],
      },
      {
        char: "🙊",
        name: "Speak-No-Evil Monkey",
        keywords: ["monkey", "mute"],
      },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    emojis: [
      {
        char: "👍",
        name: "Thumbs Up",
        keywords: ["like", "ok", "approve"],
      },
      {
        char: "👎",
        name: "Thumbs Down",
        keywords: ["dislike", "no", "reject"],
      },
      {
        char: "👊",
        name: "Oncoming Fist",
        keywords: ["fist", "punch", "bro"],
      },
      {
        char: "🤛",
        name: "Left-Facing Fist",
        keywords: ["fist", "punch", "left"],
      },
      {
        char: "🤜",
        name: "Right-Facing Fist",
        keywords: ["fist", "punch", "right"],
      },
      {
        char: "✊",
        name: "Raised Fist",
        keywords: ["power", "protest", "resist"],
      },
      {
        char: "👋",
        name: "Waving Hand",
        keywords: ["hello", "hi", "wave"],
      },
      {
        char: "🤚",
        name: "Raised Back of Hand",
        keywords: ["hand", "stop", "raise"],
      },
      {
        char: "🖐️",
        name: "Hand with Fingers Splayed",
        keywords: ["hand", "high five"],
      },
      {
        char: "✋",
        name: "Raised Hand",
        keywords: ["stop", "halt", "high five"],
      },
      {
        char: "👌",
        name: "OK Hand",
        keywords: ["ok", "perfect", "agree"],
      },
      {
        char: "🤌",
        name: "Pinched Fingers",
        keywords: ["pinch", "italian", "gesture"],
      },
      {
        char: "🤏",
        name: "Pinching Hand",
        keywords: ["small", "tiny", "pinch"],
      },
      {
        char: "✌️",
        name: "Victory Hand",
        keywords: ["peace", "two", "victory"],
      },
      {
        char: "🤞",
        name: "Crossed Fingers",
        keywords: ["luck", "wish", "hope"],
      },
      {
        char: "🤟",
        name: "Love-You Gesture",
        keywords: ["i love you", "sign language"],
      },
      {
        char: "🤘",
        name: "Sign of the Horns",
        keywords: ["rock", "metal", "party"],
      },
      {
        char: "🤙",
        name: "Call Me Hand",
        keywords: ["call me", "shaka", "hang loose"],
      },
      {
        char: "👈",
        name: "Backhand Index Pointing Left",
        keywords: ["left", "point"],
      },
      {
        char: "👉",
        name: "Backhand Index Pointing Right",
        keywords: ["right", "point"],
      },
      {
        char: "👆",
        name: "Backhand Index Pointing Up",
        keywords: ["up", "point"],
      },
      {
        char: "👇",
        name: "Backhand Index Pointing Down",
        keywords: ["down", "point"],
      },
      {
        char: "☝️",
        name: "Index Pointing Up",
        keywords: ["point", "up", "attention"],
      },
      {
        char: "✍️",
        name: "Writing Hand",
        keywords: ["write", "draw", "note"],
      },
      {
        char: "👏",
        name: "Clapping Hands",
        keywords: ["applause", "bravo", "clap"],
      },
      {
        char: "🙌",
        name: "Raising Hands",
        keywords: ["hooray", "celebrate"],
      },
      {
        char: "👐",
        name: "Open Hands",
        keywords: ["open", "hug", "offer"],
      },
      {
        char: "🤲",
        name: "Palms Together Facing Up",
        keywords: ["offering", "cupped hands"],
      },
      {
        char: "🙏",
        name: "Folded Hands",
        keywords: ["thanks", "pray", "please"],
      },
      {
        char: "🤝",
        name: "Handshake",
        keywords: ["deal", "agreement", "friend"],
      },
      {
        char: "🙌",
        name: "Raising Hands",
        keywords: ["celebration", "praise"],
      },
      {
        char: "🫶",
        name: "Heart Hands",
        keywords: ["love", "heart", "hands"],
      },
      {
        char: "🤌",
        name: "Pinched Fingers",
        keywords: ["gesture", "hand", "italian"],
      },
      { char: "👍", name: "Thumbs Up", keywords: ["ok", "good", "approve"] },
      { char: "👎", name: "Thumbs Down", keywords: ["bad", "disapprove"] },
      {
        char: "✌️",
        name: "Victory Hand",
        keywords: ["peace", "two", "victory"],
      },
      { char: "🤟", name: "Love-You Gesture", keywords: ["rock", "love"] },
      {
        char: "🤲",
        name: "Palms Up Together",
        keywords: ["please", "offer", "hands"],
      },
      {
        char: "🙏",
        name: "Folded Hands",
        keywords: ["pray", "thank", "please"],
      },
      {
        char: "👏",
        name: "Clapping Hands",
        keywords: ["applause", "bravo", "clap"],
      },
      { char: "👋", name: "Waving Hand", keywords: ["hello", "hi", "bye"] },
    ],
  },
  {
    id: "objects",
    label: "Objects & Miscellaneous",
    emojis: [
      // 🎉 Celebration & Party
      { char: "🎈", name: "Balloon", keywords: ["party", "celebrate", "fun"] },
      {
        char: "🎆",
        name: "Fireworks",
        keywords: ["celebrate", "festival", "sparkle"],
      },
      {
        char: "🎇",
        name: "Sparkler",
        keywords: ["celebrate", "sparkle", "festival"],
      },
      {
        char: "🧨",
        name: "Firecracker",
        keywords: ["bang", "celebrate", "festival"],
      },
      { char: "✨", name: "Sparkles", keywords: ["shine", "magic", "twinkle"] },
      {
        char: "🎉",
        name: "Party Popper",
        keywords: ["celebrate", "party", "fun"],
      },
      {
        char: "🎊",
        name: "Confetti Ball",
        keywords: ["party", "celebrate", "fun"],
      },

      // 🎃 Seasonal & Holiday
      {
        char: "🎃",
        name: "Jack-O-Lantern",
        keywords: ["halloween", "pumpkin", "spooky"],
      },
      {
        char: "🎄",
        name: "Christmas Tree",
        keywords: ["holiday", "xmas", "tree"],
      },
      {
        char: "🎋",
        name: "Tanabata Tree",
        keywords: ["festival", "celebrate", "japan"],
      },
      {
        char: "🎍",
        name: "Pine Decoration",
        keywords: ["japan", "celebrate", "newyear"],
      },
      {
        char: "🎎",
        name: "Japanese Dolls",
        keywords: ["festival", "japan", "celebrate"],
      },
      {
        char: "🎏",
        name: "Carp Streamer",
        keywords: ["festival", "japan", "decorate"],
      },
      {
        char: "🎐",
        name: "Wind Chime",
        keywords: ["decoration", "summer", "sound"],
      },
      {
        char: "🎑",
        name: "Moon Viewing Ceremony",
        keywords: ["festival", "moon", "celebrate"],
      },
      {
        char: "🧧",
        name: "Red Envelope",
        keywords: ["gift", "money", "celebrate"],
      },

      // 🎀 Gifts & Accessories
      { char: "🎀", name: "Ribbon", keywords: ["gift", "decorate", "pretty"] },
      {
        char: "🎁",
        name: "Wrapped Gift",
        keywords: ["present", "celebrate", "birthday"],
      },
      {
        char: "🎗️",
        name: "Reminder Ribbon",
        keywords: ["awareness", "cause", "support"],
      },

      // 🖼️ Art & Craft
      { char: "🎨", name: "Palette", keywords: ["art", "paint", "color"] },
      {
        char: "🖼️",
        name: "Framed Picture",
        keywords: ["art", "decor", "picture"],
      },
      { char: "🧵", name: "Thread", keywords: ["sewing", "craft", "stitch"] },
      { char: "🪡", name: "Needle", keywords: ["sewing", "craft", "stitch"] },
      { char: "🧶", name: "Yarn", keywords: ["knit", "craft", "wool"] },
      { char: "🪢", name: "Knot", keywords: ["rope", "tie", "craft"] },

      // 👕 Clothing & Accessories
      { char: "🧥", name: "Coat", keywords: ["clothing", "wear", "jacket"] },
      { char: "👔", name: "Necktie", keywords: ["formal", "clothing", "work"] },
      { char: "👕", name: "T-Shirt", keywords: ["clothing", "casual", "wear"] },
      { char: "👖", name: "Jeans", keywords: ["clothing", "pants", "wear"] },
      { char: "🩳", name: "Shorts", keywords: ["clothing", "summer", "wear"] },
      {
        char: "🧣",
        name: "Scarf",
        keywords: ["clothing", "winter", "accessory"],
      },
      { char: "🧤", name: "Gloves", keywords: ["clothing", "winter", "hands"] },
      { char: "🧦", name: "Socks", keywords: ["clothing", "feet", "wear"] },
      { char: "👗", name: "Dress", keywords: ["clothing", "woman", "fashion"] },
      {
        char: "🥻",
        name: "Sari",
        keywords: ["clothing", "traditional", "fashion"],
      },
      {
        char: "👘",
        name: "Kimono",
        keywords: ["clothing", "traditional", "japan"],
      },
      {
        char: "👚",
        name: "Woman’s Clothes",
        keywords: ["clothing", "fashion", "top"],
      },
      {
        char: "🪭",
        name: "Folding Fan",
        keywords: ["accessory", "cool", "decorate"],
      },
      {
        char: "🩲",
        name: "Swim Briefs",
        keywords: ["clothing", "swim", "male"],
      },
      {
        char: "🩱",
        name: "One-Piece Swimsuit",
        keywords: ["clothing", "swim", "female"],
      },
      { char: "👙", name: "Bikini", keywords: ["clothing", "swim", "female"] },

      // 👜 Bags & Shoes
      { char: "👛", name: "Purse", keywords: ["bag", "fashion", "accessory"] },
      {
        char: "👜",
        name: "Handbag",
        keywords: ["bag", "fashion", "accessory"],
      },
      {
        char: "👝",
        name: "Clutch Bag",
        keywords: ["bag", "fashion", "accessory"],
      },
      {
        char: "🛍️",
        name: "Shopping Bags",
        keywords: ["shopping", "bag", "store"],
      },
      { char: "🎒", name: "Backpack", keywords: ["bag", "school", "travel"] },
      {
        char: "🩴",
        name: "Flip-Flops",
        keywords: ["shoes", "summer", "casual"],
      },
      {
        char: "👞",
        name: "Men’s Shoes",
        keywords: ["shoes", "formal", "wear"],
      },
      { char: "👟", name: "Sneakers", keywords: ["shoes", "sport", "wear"] },
      {
        char: "🥾",
        name: "Hiking Boots",
        keywords: ["shoes", "outdoors", "wear"],
      },
      { char: "🥿", name: "Flat Shoe", keywords: ["shoes", "fashion", "wear"] },
      {
        char: "👠",
        name: "High-Heel",
        keywords: ["shoes", "fashion", "female"],
      },
      { char: "👡", name: "Sandal", keywords: ["shoes", "summer", "wear"] },
      { char: "👢", name: "Boots", keywords: ["shoes", "fashion", "wear"] },

      // 👑 Hats & Headwear
      { char: "👑", name: "Crown", keywords: ["king", "queen", "royalty"] },
      { char: "🧢", name: "Cap", keywords: ["hat", "headwear", "fashion"] },
      {
        char: "🪖",
        name: "Military Helmet",
        keywords: ["hat", "military", "protection"],
      },
      {
        char: "⛑️",
        name: "Rescue Helmet",
        keywords: ["hat", "safety", "protection"],
      },
      {
        char: "👒",
        name: "Woman’s Hat",
        keywords: ["hat", "fashion", "accessory"],
      },
      { char: "🎩", name: "Top Hat", keywords: ["hat", "fashion", "formal"] },
      {
        char: "🎓",
        name: "Graduation Cap",
        keywords: ["hat", "school", "graduate"],
      },

      // 💋 Cosmetics & Jewelry
      { char: "💋", name: "Kiss Mark", keywords: ["lipstick", "kiss", "love"] },
      {
        char: "💄",
        name: "Lipstick",
        keywords: ["makeup", "cosmetics", "fashion"],
      },
      {
        char: "💍",
        name: "Ring",
        keywords: ["jewelry", "marriage", "fashion"],
      },
      {
        char: "💎",
        name: "Gem Stone",
        keywords: ["jewel", "diamond", "luxury"],
      },
      { char: "🚗", name: "Car", keywords: ["vehicle", "transport"] },
      { char: "🚓", name: "Police Car", keywords: ["vehicle", "police"] },
      { char: "🚕", name: "Taxi", keywords: ["vehicle", "transport"] },
      { char: "🛺", name: "Auto Rickshaw", keywords: ["vehicle", "ride"] },
      { char: "🚙", name: "SUV", keywords: ["vehicle", "drive"] },
      { char: "🛻", name: "Pickup Truck", keywords: ["vehicle", "truck"] },
      { char: "🚌", name: "Bus", keywords: ["vehicle", "transport"] },
      { char: "🚐", name: "Van", keywords: ["vehicle", "transport"] },
      { char: "🚎", name: "Trolleybus", keywords: ["vehicle", "transport"] },
      { char: "🚑", name: "Ambulance", keywords: ["vehicle", "emergency"] },
      { char: "🚒", name: "Fire Truck", keywords: ["vehicle", "emergency"] },
      {
        char: "🚚",
        name: "Delivery Truck",
        keywords: ["vehicle", "transport"],
      },
      { char: "🚛", name: "Articulated Lorry", keywords: ["vehicle", "truck"] },
      { char: "🚜", name: "Tractor", keywords: ["vehicle", "farm"] },
      { char: "🚘", name: "Oncoming Car", keywords: ["vehicle", "transport"] },
      {
        char: "🚔",
        name: "Oncoming Police Car",
        keywords: ["vehicle", "police"],
      },
      { char: "🚖", name: "Oncoming Taxi", keywords: ["vehicle", "taxi"] },
      { char: "🚍", name: "Oncoming Bus", keywords: ["vehicle", "transport"] },
      {
        char: "🦽",
        name: "Manual Wheelchair",
        keywords: ["mobility", "chair"],
      },
      {
        char: "🦼",
        name: "Motorized Wheelchair",
        keywords: ["mobility", "chair"],
      },
      { char: "🛹", name: "Skateboard", keywords: ["sport", "ride"] },
      { char: "🛼", name: "Roller Skate", keywords: ["sport", "ride"] },
      { char: "🚲", name: "Bicycle", keywords: ["vehicle", "bike"] },
      { char: "🛴", name: "Kick Scooter", keywords: ["vehicle", "ride"] },
      { char: "🛵", name: "Motor Scooter", keywords: ["vehicle", "ride"] },
      { char: "🏍️", name: "Motorcycle", keywords: ["vehicle", "ride"] },
      { char: "🏎️", name: "Racing Car", keywords: ["vehicle", "race"] },
      { char: "🚄", name: "High-Speed Train", keywords: ["vehicle", "train"] },
      { char: "🚅", name: "Bullet Train", keywords: ["vehicle", "train"] },
      { char: "🚈", name: "Light Rail", keywords: ["vehicle", "train"] },
      { char: "🚝", name: "Monorail", keywords: ["vehicle", "train"] },
      { char: "🚞", name: "Mountain Railway", keywords: ["vehicle", "train"] },
      { char: "🚃", name: "Railway Car", keywords: ["vehicle", "train"] },
      { char: "🚋", name: "Tram Car", keywords: ["vehicle", "train"] },
      { char: "🚆", name: "Train", keywords: ["vehicle", "train"] },
      { char: "🚉", name: "Station", keywords: ["vehicle", "train"] },
      { char: "🚊", name: "Tram", keywords: ["vehicle", "transport"] },
      { char: "🚇", name: "Metro", keywords: ["vehicle", "train"] },
      {
        char: "🚟",
        name: "Suspension Railway",
        keywords: ["vehicle", "train"],
      },
      { char: "🚠", name: "Mountain Cableway", keywords: ["vehicle", "cable"] },
      { char: "🚡", name: "Aerial Tramway", keywords: ["vehicle", "cable"] },
      { char: "🚂", name: "Steam Locomotive", keywords: ["vehicle", "train"] },
      { char: "🛩️", name: "Small Airplane", keywords: ["aircraft", "fly"] },
      { char: "🪂", name: "Parachute", keywords: ["air", "sport"] },
      { char: "✈️", name: "Airplane", keywords: ["aircraft", "fly"] },
      { char: "🛫", name: "Airplane Departure", keywords: ["aircraft", "fly"] },
      { char: "🛬", name: "Airplane Arrival", keywords: ["aircraft", "fly"] },
      { char: "💺", name: "Seat", keywords: ["aircraft", "chair"] },
      { char: "🚁", name: "Helicopter", keywords: ["aircraft", "fly"] },
      { char: "🚀", name: "Rocket", keywords: ["space", "launch"] },
      { char: "🛸", name: "Flying Saucer", keywords: ["space", "ufo"] },
      { char: "🛰️", name: "Satellite", keywords: ["space", "orbit"] },
      { char: "⛵", name: "Sailboat", keywords: ["boat", "water"] },
      { char: "🚤", name: "Speedboat", keywords: ["boat", "water"] },
      { char: "🛥️", name: "Motor Boat", keywords: ["boat", "water"] },
      { char: "⛴️", name: "Ferry", keywords: ["boat", "water"] },
      { char: "🛳️", name: "Passenger Ship", keywords: ["boat", "water"] },
      { char: "🚢", name: "Ship", keywords: ["boat", "water"] },
      { char: "⚓", name: "Anchor", keywords: ["boat", "sea"] },
      { char: "🛟", name: "Life Buoy", keywords: ["safety", "boat"] },
      { char: "🚏", name: "Bus Stop", keywords: ["transport", "sign"] },
      { char: "⛽", name: "Fuel Pump", keywords: ["transport", "gas"] },
      { char: "🛞", name: "Wheel", keywords: ["vehicle", "transport"] },
      { char: "🚨", name: "Police Light", keywords: ["emergency", "alert"] },
      { char: "🚥", name: "Traffic Light", keywords: ["road", "signal"] },
      {
        char: "🚦",
        name: "Vertical Traffic Light",
        keywords: ["road", "signal"],
      },
      { char: "🚧", name: "Construction", keywords: ["road", "work"] },
      { char: "🏁", name: "Chequered Flag", keywords: ["race", "finish"] },
      { char: "🏳️‍🌈", name: "Rainbow Flag", keywords: ["pride", "flag"] },
      { char: "🏳️‍⚧️", name: "Transgender Flag", keywords: ["pride", "flag"] },
      { char: "🏳️", name: "White Flag", keywords: ["flag", "surrender"] },
      { char: "🏴", name: "Black Flag", keywords: ["flag"] },
      { char: "🚩", name: "Triangular Flag", keywords: ["flag", "marker"] },
      { char: "🏴‍☠️", name: "Pirate Flag", keywords: ["flag", "skull"] },
      { char: "🌌", name: "Milky Way", keywords: ["space", "stars"] },
      { char: "🪐", name: "Ringed Planet", keywords: ["space", "planet"] },
      {
        char: "🌍",
        name: "Earth Globe Europe-Africa",
        keywords: ["planet", "earth"],
      },
      {
        char: "🌎",
        name: "Earth Globe Americas",
        keywords: ["planet", "earth"],
      },
      {
        char: "🌏",
        name: "Earth Globe Asia-Australia",
        keywords: ["planet", "earth"],
      },
      { char: "🗺️", name: "World Map", keywords: ["map", "travel"] },
      { char: "🧭", name: "Compass", keywords: ["navigation", "map"] },
      {
        char: "🏔️",
        name: "Snow-Capped Mountain",
        keywords: ["mountain", "nature"],
      },
      { char: "⛰️", name: "Mountain", keywords: ["mountain", "nature"] },
      { char: "🌋", name: "Volcano", keywords: ["mountain", "nature"] },
      { char: "🗻", name: "Mount Fuji", keywords: ["mountain", "nature"] },
      { char: "🛤️", name: "Railway Track", keywords: ["train", "track"] },
      { char: "🏕️", name: "Camping", keywords: ["nature", "tent"] },
      { char: "🏞️", name: "National Park", keywords: ["nature", "park"] },
      { char: "🛣️", name: "Motorway", keywords: ["road", "transport"] },
      { char: "🏖️", name: "Beach", keywords: ["nature", "sand"] },
      { char: "🏜️", name: "Desert", keywords: ["nature", "sand"] },
      { char: "🏝️", name: "Desert Island", keywords: ["nature", "island"] },
      { char: "🏟️", name: "Stadium", keywords: ["building", "sports"] },
      {
        char: "🏛️",
        name: "Classical Building",
        keywords: ["building", "architecture"],
      },
      { char: "🏗️", name: "Construction Site", keywords: ["building", "work"] },
      { char: "🏘️", name: "Houses", keywords: ["building", "residence"] },
      { char: "🏙️", name: "Cityscape", keywords: ["building", "city"] },
      {
        char: "🏚️",
        name: "Derelict House",
        keywords: ["building", "residence"],
      },
      { char: "🏠", name: "House", keywords: ["building", "residence"] },
      {
        char: "🏡",
        name: "House with Garden",
        keywords: ["building", "residence"],
      },
      { char: "⛪", name: "Church", keywords: ["building", "religion"] },
      { char: "🕋", name: "Kaaba", keywords: ["building", "religion"] },
      { char: "🕌", name: "Mosque", keywords: ["building", "religion"] },
      { char: "🛕", name: "Hindu Temple", keywords: ["building", "religion"] },
      { char: "🕍", name: "Synagogue", keywords: ["building", "religion"] },
      { char: "⛩️", name: "Shinto Shrine", keywords: ["building", "religion"] },
      { char: "🏢", name: "Office Building", keywords: ["building", "work"] },
      { char: "🏣", name: "Japanese Post Office", keywords: ["building"] },
      { char: "🏤", name: "European Post Office", keywords: ["building"] },
      { char: "🏥", name: "Hospital", keywords: ["building", "health"] },
      { char: "🏦", name: "Bank", keywords: ["building", "finance"] },
      { char: "🏨", name: "Hotel", keywords: ["building", "accommodation"] },
      {
        char: "🏩",
        name: "Love Hotel",
        keywords: ["building", "accommodation"],
      },
      { char: "🏪", name: "Convenience Store", keywords: ["building", "shop"] },
      { char: "🏫", name: "School", keywords: ["building", "education"] },
      { char: "🏬", name: "Department Store", keywords: ["building", "shop"] },
      { char: "🏭", name: "Factory", keywords: ["building", "work"] },
      { char: "🏯", name: "Japanese Castle", keywords: ["building", "castle"] },
      { char: "🏰", name: "Castle", keywords: ["building", "castle"] },
      { char: "💒", name: "Wedding", keywords: ["building", "church"] },
      { char: "🗼", name: "Tokyo Tower", keywords: ["building", "tower"] },
      { char: "🌉", name: "Bridge at Night", keywords: ["bridge", "night"] },
      {
        char: "🗽",
        name: "Statue of Liberty",
        keywords: ["monument", "statue"],
      },
      { char: "🗾", name: "Map of Japan", keywords: ["map", "country"] },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    emojis: [
      // Plants & Weather
      {
        char: "🌙",
        name: "Crescent Moon",
        keywords: ["night", "moon", "sleep"],
      },
      {
        char: "🌸",
        name: "Cherry Blossom",
        keywords: ["flower", "pink", "sakura"],
      },
      { char: "🌊", name: "Water Wave", keywords: ["ocean", "sea", "wave"] },
      { char: "🌪️", name: "Tornado", keywords: ["storm", "wind", "weather"] },
      { char: "🪴", name: "Potted Plant", keywords: ["plant", "home", "leaf"] },
      { char: "🌈", name: "Rainbow", keywords: ["color", "happy", "weather"] },
      { char: "⛄", name: "Snowman", keywords: ["snow", "winter", "cold"] },

      // Mammals
      { char: "🐵", name: "Monkey", keywords: ["animal", "funny", "cute"] },
      { char: "🐶", name: "Dog", keywords: ["pet", "animal", "puppy"] },
      { char: "🐺", name: "Wolf", keywords: ["animal", "wild", "dog"] },
      { char: "🐱", name: "Cat", keywords: ["pet", "animal", "meow"] },
      { char: "🦁", name: "Lion", keywords: ["wild", "king", "animal"] },
      { char: "🐯", name: "Tiger", keywords: ["wild", "animal", "striped"] },
      { char: "🦒", name: "Giraffe", keywords: ["tall", "animal", "safari"] },
      { char: "🦊", name: "Fox", keywords: ["animal", "wild", "cute"] },
      { char: "🦝", name: "Raccoon", keywords: ["animal", "wild", "cute"] },
      { char: "🐮", name: "Cow", keywords: ["farm", "milk", "animal"] },
      { char: "🐷", name: "Pig", keywords: ["farm", "animal", "cute"] },
      { char: "🐗", name: "Boar", keywords: ["wild", "animal", "forest"] },
      { char: "🐭", name: "Mouse", keywords: ["small", "animal", "cute"] },
      { char: "🐹", name: "Hamster", keywords: ["small", "pet", "cute"] },
      { char: "🐰", name: "Rabbit", keywords: ["pet", "cute", "animal"] },
      { char: "🐻", name: "Bear", keywords: ["wild", "animal", "forest"] },
      {
        char: "🐻‍❄️",
        name: "Polar Bear",
        keywords: ["cold", "animal", "arctic"],
      },
      { char: "🐨", name: "Koala", keywords: ["cute", "animal", "tree"] },
      { char: "🐼", name: "Panda", keywords: ["cute", "animal", "bear"] },
      { char: "🐸", name: "Frog", keywords: ["animal", "green", "amphibian"] },
      { char: "🦓", name: "Zebra", keywords: ["animal", "wild", "striped"] },
      { char: "🐴", name: "Horse", keywords: ["animal", "ride", "farm"] },
      { char: "🫎", name: "Moose", keywords: ["wild", "antlers", "animal"] },
      { char: "🫏", name: "Donkey", keywords: ["farm", "animal", "ride"] },
      {
        char: "🦄",
        name: "Unicorn",
        keywords: ["mythical", "magic", "fantasy"],
      },
      { char: "🐔", name: "Chicken", keywords: ["farm", "animal", "bird"] },
      {
        char: "🐲",
        name: "Dragon Face",
        keywords: ["mythical", "fantasy", "fire"],
      },
      { char: "🐽", name: "Pig Nose", keywords: ["animal", "cute", "pig"] },
      {
        char: "🐾",
        name: "Paw Prints",
        keywords: ["animal", "footprints", "cute"],
      },
      {
        char: "🐒",
        name: "Monkey Face",
        keywords: ["animal", "cute", "funny"],
      },
      { char: "🦍", name: "Gorilla", keywords: ["animal", "wild", "strong"] },
      { char: "🦧", name: "Orangutan", keywords: ["animal", "wild", "cute"] },
      { char: "🦮", name: "Guide Dog", keywords: ["service", "dog", "animal"] },
      {
        char: "🐕‍🦺",
        name: "Service Dog",
        keywords: ["assistance", "dog", "help"],
      },
      { char: "🐩", name: "Poodle", keywords: ["dog", "pet", "cute"] },
      { char: "🐕", name: "Dog Face", keywords: ["dog", "pet", "animal"] },
      { char: "🐈", name: "Cat Face", keywords: ["cat", "pet", "animal"] },
      { char: "🐈‍⬛", name: "Black Cat", keywords: ["cat", "animal", "spooky"] },
      {
        char: "🐅",
        name: "Tiger Face",
        keywords: ["wild", "animal", "stripe"],
      },
      { char: "🐆", name: "Leopard", keywords: ["wild", "animal", "spots"] },
      { char: "🐎", name: "Horse Face", keywords: ["animal", "ride", "cute"] },
      { char: "🦌", name: "Deer", keywords: ["wild", "animal", "antlers"] },
      { char: "🦬", name: "Bison", keywords: ["wild", "animal", "herd"] },
      { char: "🦏", name: "Rhinoceros", keywords: ["wild", "animal", "horn"] },
      {
        char: "🦛",
        name: "Hippopotamus",
        keywords: ["wild", "animal", "river"],
      },
      { char: "🐂", name: "Ox", keywords: ["farm", "strong", "animal"] },
      {
        char: "🐃",
        name: "Water Buffalo",
        keywords: ["farm", "animal", "strong"],
      },
      { char: "🐄", name: "Cow Face", keywords: ["farm", "animal", "milk"] },
      { char: "🐖", name: "Pig Face", keywords: ["farm", "animal", "cute"] },
      { char: "🐏", name: "Ram", keywords: ["animal", "horns", "sheep"] },
      { char: "🐑", name: "Ewe", keywords: ["animal", "sheep", "farm"] },
      { char: "🐐", name: "Goat", keywords: ["farm", "animal", "cute"] },
      { char: "🐪", name: "Camel", keywords: ["desert", "animal", "hump"] },
      {
        char: "🐫",
        name: "Two-Hump Camel",
        keywords: ["desert", "animal", "hump"],
      },
      { char: "🦙", name: "Llama", keywords: ["animal", "cute", "wool"] },
      {
        char: "🦘",
        name: "Kangaroo",
        keywords: ["animal", "jump", "australia"],
      },
      { char: "🦥", name: "Sloth", keywords: ["animal", "lazy", "cute"] },
      { char: "🦨", name: "Skunk", keywords: ["animal", "wild", "stinky"] },
      { char: "🦡", name: "Badger", keywords: ["animal", "wild", "forest"] },
      { char: "🐘", name: "Elephant", keywords: ["animal", "big", "tusk"] },
      {
        char: "🦣",
        name: "Mammoth",
        keywords: ["prehistoric", "animal", "tusk"],
      },
      { char: "🐁", name: "Mouse Face", keywords: ["animal", "cute", "small"] },
      { char: "🐀", name: "Rat", keywords: ["animal", "rodent", "cute"] },
      { char: "🦔", name: "Hedgehog", keywords: ["animal", "cute", "small"] },
      { char: "🐇", name: "Rabbit Face", keywords: ["animal", "cute", "pet"] },
      { char: "🐿️", name: "Chipmunk", keywords: ["animal", "cute", "small"] },
      { char: "🦫", name: "Beaver", keywords: ["animal", "wood", "dam"] },
      { char: "🦎", name: "Lizard", keywords: ["animal", "reptile", "wild"] },
      {
        char: "🐊",
        name: "Crocodile",
        keywords: ["animal", "reptile", "wild"],
      },
      { char: "🐢", name: "Turtle", keywords: ["animal", "reptile", "slow"] },
      { char: "🐍", name: "Snake", keywords: ["animal", "reptile", "slither"] },
      { char: "🐉", name: "Dragon", keywords: ["mythical", "fantasy", "fire"] },
      {
        char: "🦕",
        name: "Sauropod",
        keywords: ["dinosaur", "prehistoric", "animal"],
      },
      {
        char: "🦖",
        name: "T-Rex",
        keywords: ["dinosaur", "prehistoric", "animal"],
      },
      { char: "🦦", name: "Otter", keywords: ["animal", "cute", "river"] },
      { char: "🦈", name: "Shark", keywords: ["animal", "ocean", "wild"] },
      { char: "🐬", name: "Dolphin", keywords: ["animal", "ocean", "cute"] },
      { char: "🦭", name: "Seal", keywords: ["animal", "ocean", "cute"] },
      { char: "🐳", name: "Whale", keywords: ["animal", "ocean", "big"] },
      { char: "🐋", name: "Whale Face", keywords: ["animal", "ocean", "cute"] },
      { char: "🐟", name: "Fish", keywords: ["animal", "ocean", "swim"] },
      {
        char: "🐠",
        name: "Tropical Fish",
        keywords: ["animal", "ocean", "colorful"],
      },
      {
        char: "🐡",
        name: "Puffer Fish",
        keywords: ["animal", "ocean", "spiky"],
      },
      {
        char: "🦐",
        name: "Shrimp",
        keywords: ["animal", "ocean", "crustacean"],
      },
      { char: "🦑", name: "Squid", keywords: ["animal", "ocean", "tentacle"] },
      {
        char: "🐙",
        name: "Octopus",
        keywords: ["animal", "ocean", "tentacle"],
      },
      {
        char: "🦞",
        name: "Lobster",
        keywords: ["animal", "ocean", "crustacean"],
      },
      { char: "🦀", name: "Crab", keywords: ["animal", "ocean", "crustacean"] },
      {
        char: "🐚",
        name: "Spiral Shell",
        keywords: ["ocean", "beach", "shell"],
      },
      { char: "🦆", name: "Duck", keywords: ["animal", "bird", "cute"] },
      { char: "🐓", name: "Rooster", keywords: ["animal", "farm", "bird"] },
      { char: "🦃", name: "Turkey", keywords: ["animal", "bird", "farm"] },
      { char: "🦅", name: "Eagle", keywords: ["animal", "bird", "wild"] },
      { char: "🕊️", name: "Dove", keywords: ["animal", "bird", "peace"] },
      { char: "🦢", name: "Swan", keywords: ["animal", "bird", "elegant"] },
      { char: "🦜", name: "Parrot", keywords: ["animal", "bird", "colorful"] },
      { char: "🦩", name: "Flamingo", keywords: ["animal", "bird", "pink"] },
      { char: "🦚", name: "Peacock", keywords: ["animal", "bird", "colorful"] },
      { char: "🦉", name: "Owl", keywords: ["animal", "bird", "night"] },
      { char: "🦤", name: "Dodo", keywords: ["extinct", "bird", "funny"] },
      { char: "🪶", name: "Feather", keywords: ["bird", "light", "soft"] },
      { char: "🐦", name: "Bird", keywords: ["animal", "fly", "cute"] },
      { char: "🐧", name: "Penguin", keywords: ["animal", "bird", "cold"] },
      { char: "🐥", name: "Chick", keywords: ["animal", "bird", "cute"] },
      { char: "🐤", name: "Baby Chick", keywords: ["animal", "bird", "cute"] },
      {
        char: "🐣",
        name: "Hatching Chick",
        keywords: ["animal", "bird", "baby"],
      },
      { char: "🦇", name: "Bat", keywords: ["animal", "night", "spooky"] },
      { char: "🦋", name: "Butterfly", keywords: ["animal", "insect", "fly"] },
      { char: "🐌", name: "Snail", keywords: ["animal", "slow", "shell"] },
      {
        char: "🐛",
        name: "Caterpillar",
        keywords: ["animal", "insect", "cute"],
      },
      { char: "🦟", name: "Mosquito", keywords: ["insect", "bite", "animal"] },
      { char: "🪰", name: "Fly", keywords: ["insect", "bug", "animal"] },
      { char: "🪱", name: "Worm", keywords: ["insect", "bug", "animal"] },
      { char: "🦗", name: "Cricket", keywords: ["insect", "bug", "animal"] },
      { char: "🐜", name: "Ant", keywords: ["insect", "bug", "small"] },
      { char: "🪳", name: "Cockroach", keywords: ["insect", "bug", "pest"] },
      { char: "🐝", name: "Bee", keywords: ["insect", "honey", "bug"] },
      { char: "🪲", name: "Beetle", keywords: ["insect", "bug", "animal"] },
      { char: "🐞", name: "Lady Beetle", keywords: ["insect", "bug", "cute"] },
      { char: "🦂", name: "Scorpion", keywords: ["insect", "wild", "danger"] },
      { char: "🕷️", name: "Spider", keywords: ["insect", "web", "scary"] },
      { char: "🕸️", name: "Spider Web", keywords: ["web", "spooky", "insect"] },
      { char: "🦠", name: "Microbe", keywords: ["germ", "virus", "bacteria"] },
      // Fruits
      {
        char: "🥝",
        name: "Kiwi Fruit",
        keywords: ["fruit", "food", "healthy"],
      },
      { char: "🥥", name: "Coconut", keywords: ["fruit", "food", "tropical"] },
      { char: "🍇", name: "Grapes", keywords: ["fruit", "food", "healthy"] },
      { char: "🍈", name: "Melon", keywords: ["fruit", "food", "sweet"] },
      { char: "🍉", name: "Watermelon", keywords: ["fruit", "food", "summer"] },
      { char: "🍊", name: "Tangerine", keywords: ["fruit", "food", "citrus"] },
      { char: "🍋", name: "Lemon", keywords: ["fruit", "food", "citrus"] },
      {
        char: "🍋‍🟩",
        name: "Lemon Slice",
        keywords: ["fruit", "food", "citrus"],
      },
      { char: "🍌", name: "Banana", keywords: ["fruit", "food", "yellow"] },
      {
        char: "🍍",
        name: "Pineapple",
        keywords: ["fruit", "food", "tropical"],
      },
      { char: "🥭", name: "Mango", keywords: ["fruit", "food", "tropical"] },
      { char: "🍎", name: "Red Apple", keywords: ["fruit", "food", "apple"] },
      { char: "🍏", name: "Green Apple", keywords: ["fruit", "food", "apple"] },
      { char: "🍐", name: "Pear", keywords: ["fruit", "food", "healthy"] },
      { char: "🍑", name: "Peach", keywords: ["fruit", "food", "sweet"] },
      { char: "🍒", name: "Cherries", keywords: ["fruit", "food", "sweet"] },
      { char: "🍓", name: "Strawberry", keywords: ["fruit", "food", "sweet"] },
      { char: "🫐", name: "Blueberry", keywords: ["fruit", "food", "berry"] },

      // Vegetables
      { char: "🍅", name: "Tomato", keywords: ["vegetable", "food", "red"] },
      { char: "🫒", name: "Olive", keywords: ["vegetable", "food", "green"] },
      {
        char: "🍆",
        name: "Eggplant",
        keywords: ["vegetable", "food", "purple"],
      },
      {
        char: "🌽",
        name: "Ear of Corn",
        keywords: ["vegetable", "food", "yellow"],
      },
      {
        char: "🌶️",
        name: "Hot Pepper",
        keywords: ["vegetable", "spicy", "red"],
      },
      {
        char: "🫑",
        name: "Bell Pepper",
        keywords: ["vegetable", "food", "green"],
      },
      {
        char: "🍄",
        name: "Mushroom",
        keywords: ["vegetable", "food", "fungi"],
      },
      { char: "🥑", name: "Avocado", keywords: ["vegetable", "food", "green"] },
      {
        char: "🥒",
        name: "Cucumber",
        keywords: ["vegetable", "food", "green"],
      },
      {
        char: "🥬",
        name: "Leafy Green",
        keywords: ["vegetable", "food", "healthy"],
      },
      {
        char: "🥦",
        name: "Broccoli",
        keywords: ["vegetable", "food", "healthy"],
      },
      {
        char: "🥔",
        name: "Potato",
        keywords: ["vegetable", "food", "starchy"],
      },
      {
        char: "🧄",
        name: "Garlic",
        keywords: ["vegetable", "food", "seasoning"],
      },
      {
        char: "🧅",
        name: "Onion",
        keywords: ["vegetable", "food", "seasoning"],
      },
      { char: "🥕", name: "Carrot", keywords: ["vegetable", "food", "orange"] },
      { char: "🌰", name: "Chestnut", keywords: ["vegetable", "food", "nut"] },
      { char: "🫚", name: "Galangal", keywords: ["vegetable", "food", "spice"] },
      { char: "🫛", name: "Pea Pod", keywords: ["vegetable", "food", "green"] },
      {
        char: "🍄‍🟫",
        name: "Brown Mushroom",
        keywords: ["vegetable", "food", "fungi"],
      },
      { char: "🥜", name: "Peanuts", keywords: ["vegetable", "food", "nut"] },
      { char: "🫘", name: "Beans", keywords: ["vegetable", "food", "protein"] },
      // Flowers & Plants
      { char: "💐", name: "Bouquet", keywords: ["flower", "gift", "nature"] },
      {
        char: "🌸",
        name: "Cherry Blossom",
        keywords: ["flower", "nature", "pink"],
      },
      {
        char: "🏵️",
        name: "Rosette",
        keywords: ["flower", "nature", "decorative"],
      },
      { char: "🌹", name: "Rose", keywords: ["flower", "nature", "love"] },
      {
        char: "🌺",
        name: "Hibiscus",
        keywords: ["flower", "nature", "tropical"],
      },
      {
        char: "🌻",
        name: "Sunflower",
        keywords: ["flower", "nature", "yellow"],
      },
      { char: "🌼", name: "Blossom", keywords: ["flower", "nature", "yellow"] },
      { char: "🌷", name: "Tulip", keywords: ["flower", "nature", "spring"] },
      { char: "🪻", name: "Hyacinth", keywords: ["flower", "nature", "purple"] },
      {
        char: "🥀",
        name: "Wilted Flower",
        keywords: ["flower", "nature", "sad"],
      },
      { char: "☘️", name: "Shamrock", keywords: ["plant", "nature", "green"] },
      { char: "🌱", name: "Seedling", keywords: ["plant", "nature", "growth"] },
      {
        char: "🪴",
        name: "Potted Plant",
        keywords: ["plant", "nature", "home"],
      },
      {
        char: "🌲",
        name: "Evergreen Tree",
        keywords: ["plant", "nature", "tree"],
      },
      {
        char: "🌳",
        name: "Deciduous Tree",
        keywords: ["plant", "nature", "tree"],
      },
      {
        char: "🌴",
        name: "Palm Tree",
        keywords: ["plant", "nature", "tropical"],
      },
      { char: "🌵", name: "Cactus", keywords: ["plant", "nature", "desert"] },
      {
        char: "🌾",
        name: "Sheaf of Rice",
        keywords: ["plant", "nature", "crop"],
      },
      { char: "🌿", name: "Herb", keywords: ["plant", "nature", "green"] },
      {
        char: "🍀",
        name: "Four Leaf Clover",
        keywords: ["plant", "luck", "green"],
      },
      { char: "🍁", name: "Maple Leaf", keywords: ["plant", "nature", "fall"] },
      {
        char: "🍂",
        name: "Fallen Leaf",
        keywords: ["plant", "nature", "fall"],
      },
      {
        char: "🍃",
        name: "Leaf Fluttering",
        keywords: ["plant", "nature", "green"],
      },
      { char: "🪹", name: "Bird Nest", keywords: ["nature", "home", "bird"] },
      { char: "🪺", name: "Empty Nest", keywords: ["nature", "home", "bird"] },
    ],
  },
  {
    id: "people",
    label: "People & Activities",
    emojis: [
      // Basic People
      { char: "👩", name: "Woman", keywords: ["female", "person", "adult"] },
      { char: "👨", name: "Man", keywords: ["male", "person", "adult"] },
      { char: "🧑", name: "Person", keywords: ["adult", "human", "neutral"] },
      { char: "👧", name: "Girl", keywords: ["female", "child", "kid"] },
      { char: "👦", name: "Boy", keywords: ["male", "child", "kid"] },
      { char: "🧒", name: "Child", keywords: ["kid", "human", "young"] },
      { char: "👶", name: "Baby", keywords: ["infant", "child", "cute"] },
      {
        char: "👵",
        name: "Old Woman",
        keywords: ["elderly", "female", "senior"],
      },
      { char: "👴", name: "Old Man", keywords: ["elderly", "male", "senior"] },
      {
        char: "🧓",
        name: "Older Adult",
        keywords: ["elderly", "adult", "senior"],
      },

      // Hair Variations
      {
        char: "👩‍🦰",
        name: "Woman: Red Hair",
        keywords: ["woman", "red", "hair"],
      },
      { char: "👨‍🦰", name: "Man: Red Hair", keywords: ["man", "red", "hair"] },
      {
        char: "🧑‍🦰",
        name: "Person: Red Hair",
        keywords: ["person", "red", "hair"],
      },
      {
        char: "👩‍🦱",
        name: "Woman: Curly Hair",
        keywords: ["woman", "curly", "hair"],
      },
      {
        char: "👨‍🦱",
        name: "Man: Curly Hair",
        keywords: ["man", "curly", "hair"],
      },
      {
        char: "🧑‍🦱",
        name: "Person: Curly Hair",
        keywords: ["person", "curly", "hair"],
      },
      { char: "👩‍🦲", name: "Woman: Bald", keywords: ["woman", "bald", "hair"] },
      { char: "👨‍🦲", name: "Man: Bald", keywords: ["man", "bald", "hair"] },
      {
        char: "🧑‍🦲",
        name: "Person: Bald",
        keywords: ["person", "bald", "hair"],
      },
      {
        char: "👩‍🦳",
        name: "Woman: White Hair",
        keywords: ["woman", "white", "hair"],
      },
      {
        char: "👨‍🦳",
        name: "Man: White Hair",
        keywords: ["man", "white", "hair"],
      },
      {
        char: "🧑‍🦳",
        name: "Person: White Hair",
        keywords: ["person", "white", "hair"],
      },

      // Professionals & Roles
      {
        char: "👩‍⚕️",
        name: "Woman Health Worker",
        keywords: ["doctor", "nurse", "medical"],
      },
      {
        char: "👨‍⚕️",
        name: "Man Health Worker",
        keywords: ["doctor", "nurse", "medical"],
      },
      {
        char: "🧑‍⚕️",
        name: "Person Health Worker",
        keywords: ["doctor", "nurse", "medical"],
      },
      {
        char: "👩‍🎓",
        name: "Woman Student",
        keywords: ["graduate", "study", "learn"],
      },
      {
        char: "👨‍🎓",
        name: "Man Student",
        keywords: ["graduate", "study", "learn"],
      },
      {
        char: "🧑‍🎓",
        name: "Person Student",
        keywords: ["graduate", "study", "learn"],
      },
      {
        char: "👩‍🏫",
        name: "Woman Teacher",
        keywords: ["teach", "instructor", "school"],
      },
      {
        char: "👨‍🏫",
        name: "Man Teacher",
        keywords: ["teach", "instructor", "school"],
      },
      {
        char: "🧑‍🏫",
        name: "Person Teacher",
        keywords: ["teach", "instructor", "school"],
      },
      {
        char: "👩‍⚖️",
        name: "Woman Judge",
        keywords: ["law", "justice", "court"],
      },
      { char: "👨‍⚖️", name: "Man Judge", keywords: ["law", "justice", "court"] },
      {
        char: "🧑‍⚖️",
        name: "Person Judge",
        keywords: ["law", "justice", "court"],
      },

      // Activities & Sports
      {
        char: "🏃‍♀️",
        name: "Woman Running",
        keywords: ["run", "exercise", "female"],
      },
      {
        char: "🏃‍♂️",
        name: "Man Running",
        keywords: ["run", "exercise", "male"],
      },
      { char: "🏃", name: "Person Running", keywords: ["run", "exercise"] },
      {
        char: "💃",
        name: "Woman Dancing",
        keywords: ["dance", "party", "female"],
      },
      { char: "🕺", name: "Man Dancing", keywords: ["dance", "party", "male"] },
      {
        char: "🧘‍♀️",
        name: "Woman Meditating",
        keywords: ["meditate", "yoga", "female"],
      },
      {
        char: "🧘‍♂️",
        name: "Man Meditating",
        keywords: ["meditate", "yoga", "male"],
      },
      {
        char: "🧗‍♀️",
        name: "Woman Climbing",
        keywords: ["climb", "rock", "female"],
      },
      { char: "🧗‍♂️", name: "Man Climbing", keywords: ["climb", "rock", "male"] },
      {
        char: "🏄‍♀️",
        name: "Woman Surfing",
        keywords: ["surf", "ocean", "female"],
      },
      { char: "🏄‍♂️", name: "Man Surfing", keywords: ["surf", "ocean", "male"] },
      {
        char: "🚴‍♀️",
        name: "Woman Biking",
        keywords: ["bike", "ride", "exercise"],
      },
      {
        char: "🚴‍♂️",
        name: "Man Biking",
        keywords: ["bike", "ride", "exercise"],
      },
    ],
  },
  {
    id: "food-nature",
    label: "Food & Nature",
    emojis: [
      // 🍕 Fast Food
      { char: "🍕", name: "Pizza", keywords: ["food", "fastfood", "cheese"] },
      {
        char: "🍔",
        name: "Hamburger",
        keywords: ["food", "burger", "fastfood"],
      },
      {
        char: "🍟",
        name: "French Fries",
        keywords: ["food", "fastfood", "snack"],
      },
      {
        char: "🌭",
        name: "Hot Dog",
        keywords: ["food", "fastfood", "sausage"],
      },
      { char: "🍿", name: "Popcorn", keywords: ["snack", "movie", "food"] },
      {
        char: "🧂",
        name: "Salt",
        keywords: ["seasoning", "food", "condiment"],
      },

      // 🍳 Breakfast / Cooking
      { char: "🥓", name: "Bacon", keywords: ["food", "breakfast", "meat"] },
      { char: "🥚", name: "Egg", keywords: ["food", "breakfast", "protein"] },
      { char: "🍳", name: "Cooking", keywords: ["food", "fry", "breakfast"] },
      { char: "🧇", name: "Waffle", keywords: ["food", "breakfast", "sweet"] },
      {
        char: "🥞",
        name: "Pancakes",
        keywords: ["food", "breakfast", "sweet"],
      },
      { char: "🧈", name: "Butter", keywords: ["food", "spread", "cooking"] },
      { char: "🍞", name: "Bread", keywords: ["food", "bakery", "toast"] },
      { char: "🥐", name: "Croissant", keywords: ["food", "bakery", "pastry"] },
      { char: "🥨", name: "Pretzel", keywords: ["food", "snack", "bakery"] },
      { char: "🥯", name: "Bagel", keywords: ["food", "bakery", "breakfast"] },
      { char: "🥖", name: "Baguette", keywords: ["food", "bread", "bakery"] },
      { char: "🫓", name: "Flatbread", keywords: ["food", "bread", "baking"] },
      { char: "🧀", name: "Cheese", keywords: ["food", "dairy", "snack"] },

      // 🥗 Healthy / Meals
      { char: "🥗", name: "Salad", keywords: ["food", "healthy", "vegetable"] },
      {
        char: "🥙",
        name: "Stuffed Flatbread",
        keywords: ["food", "meal", "mediterranean"],
      },
      { char: "🥪", name: "Sandwich", keywords: ["food", "lunch", "meal"] },
      { char: "🌮", name: "Taco", keywords: ["food", "mexican", "meal"] },
      { char: "🌯", name: "Burrito", keywords: ["food", "mexican", "meal"] },
      { char: "🫔", name: "Tamale", keywords: ["food", "mexican", "meal"] },

      // 🥩 Meat / Protein
      {
        char: "🥫",
        name: "Canned Food",
        keywords: ["food", "preserved", "meal"],
      },
      {
        char: "🍖",
        name: "Meat on Bone",
        keywords: ["food", "meat", "dinner"],
      },
      {
        char: "🍗",
        name: "Poultry Leg",
        keywords: ["food", "meat", "chicken"],
      },
      { char: "🥩", name: "Steak", keywords: ["food", "meat", "protein"] },
      {
        char: "🍠",
        name: "Roasted Sweet Potato",
        keywords: ["food", "vegetable", "meal"],
      },

      // 🍣 Asian Cuisine
      { char: "🥟", name: "Dumpling", keywords: ["food", "asian", "meal"] },
      {
        char: "🥠",
        name: "Fortune Cookie",
        keywords: ["food", "asian", "snack"],
      },
      { char: "🥡", name: "Takeout Box", keywords: ["food", "asian", "meal"] },
      { char: "🍱", name: "Bento Box", keywords: ["food", "asian", "meal"] },
      {
        char: "🍘",
        name: "Rice Cracker",
        keywords: ["food", "snack", "asian"],
      },
      { char: "🍙", name: "Rice Ball", keywords: ["food", "asian", "meal"] },
      { char: "🍚", name: "Cooked Rice", keywords: ["food", "meal", "grain"] },
      { char: "🍛", name: "Curry Rice", keywords: ["food", "meal", "asian"] },
      {
        char: "🍜",
        name: "Steaming Bowl",
        keywords: ["food", "noodle", "meal"],
      },
      { char: "🦪", name: "Oyster", keywords: ["food", "seafood", "meal"] },
      { char: "🍣", name: "Sushi", keywords: ["food", "japanese", "meal"] },
      {
        char: "🍤",
        name: "Fried Shrimp",
        keywords: ["food", "seafood", "meal"],
      },
      {
        char: "🍥",
        name: "Fish Cake with Swirl",
        keywords: ["food", "asian", "meal"],
      },
      { char: "🥮", name: "Moon Cake", keywords: ["food", "asian", "dessert"] },
      { char: "🍢", name: "Oden", keywords: ["food", "skewer", "meal"] },
      { char: "🧆", name: "Falafel", keywords: ["food", "vegetarian", "meal"] },
      {
        char: "🥘",
        name: "Shallow Pan of Food",
        keywords: ["food", "meal", "dish"],
      },
      { char: "🍲", name: "Pot of Food", keywords: ["food", "meal", "stew"] },
      { char: "🫕", name: "Fondue", keywords: ["food", "cheese", "meal"] },
      { char: "🍝", name: "Spaghetti", keywords: ["food", "pasta", "meal"] },
      {
        char: "🥣",
        name: "Bowl with Spoon",
        keywords: ["food", "meal", "breakfast"],
      },

      // 🍰 Dessert & Sweet
      { char: "🥧", name: "Pie", keywords: ["food", "dessert", "sweet"] },
      {
        char: "🍦",
        name: "Soft Ice Cream",
        keywords: ["food", "dessert", "icecream"],
      },
      {
        char: "🍧",
        name: "Shaved Ice",
        keywords: ["food", "dessert", "sweet"],
      },
      { char: "🍨", name: "Ice Cream", keywords: ["food", "dessert", "sweet"] },
      { char: "🍩", name: "Doughnut", keywords: ["food", "dessert", "sweet"] },
      { char: "🍪", name: "Cookie", keywords: ["food", "dessert", "sweet"] },
      {
        char: "🎂",
        name: "Birthday Cake",
        keywords: ["food", "dessert", "celebration"],
      },
      { char: "🍰", name: "Cake", keywords: ["food", "dessert", "sweet"] },
      { char: "🧁", name: "Cupcake", keywords: ["food", "dessert", "sweet"] },
      {
        char: "🍫",
        name: "Chocolate Bar",
        keywords: ["food", "sweet", "snack"],
      },
      { char: "🍬", name: "Candy", keywords: ["food", "sweet", "snack"] },
      { char: "🍭", name: "Lollipop", keywords: ["food", "sweet", "candy"] },
      { char: "🍡", name: "Dango", keywords: ["food", "sweet", "asian"] },
      { char: "🍮", name: "Custard", keywords: ["food", "dessert", "sweet"] },
      { char: "🍯", name: "Honey Pot", keywords: ["food", "sweet", "natural"] },
      {
        char: "🍼",
        name: "Baby Bottle",
        keywords: ["drink", "milk", "feeding"],
      },
      {
        char: "🥛",
        name: "Glass of Milk",
        keywords: ["drink", "milk", "beverage"],
      },
      {
        char: "🧃",
        name: "Juice Box",
        keywords: ["drink", "juice", "beverage"],
      },
      {
        char: "☕",
        name: "Hot Beverage",
        keywords: ["coffee", "tea", "drink"],
      },
      { char: "🫖", name: "Teapot", keywords: ["drink", "tea", "hot"] },
      { char: "🍵", name: "Tea Cup", keywords: ["drink", "tea", "hot"] },
      {
        char: "🧉",
        name: "Mate Drink",
        keywords: ["drink", "beverage", "hot"],
      },
      { char: "🍶", name: "Sake", keywords: ["drink", "alcohol", "japanese"] },
      {
        char: "🍾",
        name: "Champagne Bottle",
        keywords: ["drink", "celebration", "alcohol"],
      },
      {
        char: "🍷",
        name: "Wine Glass",
        keywords: ["drink", "alcohol", "beverage"],
      },
      {
        char: "🍸",
        name: "Cocktail Glass",
        keywords: ["drink", "alcohol", "beverage"],
      },
      // Drinks continued
      {
        char: "🍹",
        name: "Tropical Drink",
        keywords: ["drink", "cocktail", "beverage"],
      },
      { char: "🍺", name: "Beer Mug", keywords: ["drink", "beer", "alcohol"] },
      {
        char: "🍻",
        name: "Clinking Beer Mugs",
        keywords: ["drink", "cheers", "beer"],
      },
      {
        char: "🥂",
        name: "Clinking Glasses",
        keywords: ["drink", "celebration", "cheers"],
      },
      {
        char: "🥃",
        name: "Whiskey Glass",
        keywords: ["drink", "alcohol", "beverage"],
      },
      {
        char: "🫗",
        name: "Pouring Liquid",
        keywords: ["drink", "pour", "beverage"],
      },
      { char: "🧊", name: "Ice Cube", keywords: ["drink", "cold", "ice"] },
      {
        char: "🥤",
        name: "Cup with Straw",
        keywords: ["drink", "soda", "beverage"],
      },
      { char: "🧋", name: "Bubble Tea", keywords: ["drink", "tea", "boba"] },

      // Utensils / Tableware
      {
        char: "🥢",
        name: "Chopsticks",
        keywords: ["utensil", "food", "asian"],
      },
      {
        char: "🍽️",
        name: "Fork and Knife with Plate",
        keywords: ["utensil", "meal", "dining"],
      },
      {
        char: "🍴",
        name: "Fork and Knife",
        keywords: ["utensil", "dining", "meal"],
      },
      { char: "🥄", name: "Spoon", keywords: ["utensil", "food", "meal"] },
      {
        char: "🏺",
        name: "Amphora",
        keywords: ["container", "pottery", "drink"],
      },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    emojis: [
      { char: "❤️", name: "Red Heart", keywords: ["love", "heart"] },
      { char: "🩷", name: "Pink Heart", keywords: ["love", "heart"] },
      { char: "🧡", name: "Orange Heart", keywords: ["love", "heart"] },
      { char: "💛", name: "Yellow Heart", keywords: ["love", "heart"] },
      { char: "💚", name: "Green Heart", keywords: ["love", "heart"] },
      { char: "💙", name: "Blue Heart", keywords: ["love", "heart"] },
      { char: "🩵", name: "Light Blue Heart", keywords: ["love", "heart"] },
      { char: "💜", name: "Purple Heart", keywords: ["love", "heart"] },
      { char: "🤎", name: "Brown Heart", keywords: ["love", "heart"] },
      { char: "🖤", name: "Black Heart", keywords: ["love", "heart"] },
      { char: "🩶", name: "Grey Heart", keywords: ["love", "heart"] },
      { char: "🤍", name: "White Heart", keywords: ["love", "heart"] },
      {
        char: "💔",
        name: "Broken Heart",
        keywords: ["love", "heart", "break"],
      },
      {
        char: "❤️‍🔥",
        name: "Heart on Fire",
        keywords: ["love", "heart", "fire"],
      },
      {
        char: "❤️‍🩹",
        name: "Mending Heart",
        keywords: ["love", "heart", "heal"],
      },
      { char: "❣️", name: "Heart Exclamation", keywords: ["love", "heart"] },
      { char: "💕", name: "Two Hearts", keywords: ["love", "heart"] },
      { char: "💞", name: "Revolving Hearts", keywords: ["love", "heart"] },
      { char: "💓", name: "Beating Heart", keywords: ["love", "heart"] },
      { char: "💗", name: "Growing Heart", keywords: ["love", "heart"] },
      { char: "💖", name: "Sparkling Heart", keywords: ["love", "heart"] },
      { char: "💘", name: "Heart with Arrow", keywords: ["love", "heart"] },
      { char: "💝", name: "Heart with Ribbon", keywords: ["love", "heart"] },
      { char: "💟", name: "Heart Decoration", keywords: ["love", "heart"] },
      { char: "💌", name: "Love Letter", keywords: ["love", "letter"] },
      { char: "💢", name: "Anger Symbol", keywords: ["anger", "symbol"] },
      { char: "💥", name: "Collision", keywords: ["explosion", "impact"] },
      { char: "💤", name: "Zzz", keywords: ["sleep", "tired"] },
      { char: "💦", name: "Sweat Droplets", keywords: ["water", "droplet"] },
      { char: "💨", name: "Dashing Away", keywords: ["wind", "speed"] },
      { char: "💫", name: "Dizzy", keywords: ["star", "sparkle"] },
      { char: "🕳️", name: "Hole", keywords: ["hole", "black"] },
      { char: "☮️", name: "Peace Symbol", keywords: ["peace", "symbol"] },
      { char: "✝️", name: "Latin Cross", keywords: ["religion", "cross"] },
      {
        char: "☪️",
        name: "Star and Crescent",
        keywords: ["religion", "islam"],
      },
      { char: "🕉️", name: "Om", keywords: ["religion", "hindu"] },
      {
        char: "☸️",
        name: "Wheel of Dharma",
        keywords: ["religion", "buddhism"],
      },
      { char: "✡️", name: "Star of David", keywords: ["religion", "jewish"] },
      {
        char: "🔯",
        name: "Six Pointed Star with Dot",
        keywords: ["symbol", "star"],
      },
      { char: "🪯", name: "Hamsa", keywords: ["symbol", "protection"] },
      { char: "🕎", name: "Menorah", keywords: ["religion", "jewish"] },
      { char: "☯️", name: "Yin Yang", keywords: ["symbol", "balance"] },
      { char: "☦️", name: "Orthodox Cross", keywords: ["religion", "cross"] },
      {
        char: "🛐",
        name: "Place of Worship",
        keywords: ["religion", "symbol"],
      },
      { char: "⛎", name: "Ophiuchus", keywords: ["zodiac", "symbol"] },
      { char: "♈", name: "Aries", keywords: ["zodiac", "astrology"] },
      { char: "♉", name: "Taurus", keywords: ["zodiac", "astrology"] },
      { char: "♊", name: "Gemini", keywords: ["zodiac", "astrology"] },
      { char: "♋", name: "Cancer", keywords: ["zodiac", "astrology"] },
      { char: "♌", name: "Leo", keywords: ["zodiac", "astrology"] },
      { char: "♍", name: "Virgo", keywords: ["zodiac", "astrology"] },
      { char: "♎", name: "Libra", keywords: ["zodiac", "astrology"] },
      { char: "♏", name: "Scorpio", keywords: ["zodiac", "astrology"] },
      { char: "♐", name: "Sagittarius", keywords: ["zodiac", "astrology"] },
      { char: "♑", name: "Capricorn", keywords: ["zodiac", "astrology"] },
      { char: "♒", name: "Aquarius", keywords: ["zodiac", "astrology"] },
      { char: "♓", name: "Pisces", keywords: ["zodiac", "astrology"] },
      { char: "🆔", name: "ID Button", keywords: ["symbol", "id"] },
      { char: "⚕️", name: "Medical Symbol", keywords: ["symbol", "medical"] },
      { char: "♾️", name: "Infinity", keywords: ["symbol", "infinity"] },
      { char: "⚛️", name: "Atom Symbol", keywords: ["symbol", "science"] },
      {
        char: "🈳",
        name: "Japanese Vacant Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈹",
        name: "Japanese Discount Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈶",
        name: "Japanese Here Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈚",
        name: "Japanese Free Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈸",
        name: "Japanese Application Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈺",
        name: "Japanese Open for Business Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈷️",
        name: "Japanese Monthly Amount Button",
        keywords: ["symbol", "japanese"],
      },
      { char: "✴️", name: "Eight-Pointed Star", keywords: ["symbol", "star"] },
      { char: "🆚", name: "VS Button", keywords: ["symbol", "vs"] },
      {
        char: "🉑",
        name: "Acceptable Button",
        keywords: ["symbol", "approval"],
      },
      { char: "💮", name: "White Flower", keywords: ["symbol", "flower"] },
      { char: "🪷", name: "Lotus", keywords: ["symbol", "flower"] },
      {
        char: "🉐",
        name: "Japanese Prohibited Button",
        keywords: ["symbol", "japanese"],
      },
      { char: "㊙️", name: "Secret Button", keywords: ["symbol", "secret"] },
      {
        char: "㊗️",
        name: "Congratulation Button",
        keywords: ["symbol", "congratulation"],
      },
      {
        char: "🈴",
        name: "Japanese Passing Grade Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈵",
        name: "Japanese Full Button",
        keywords: ["symbol", "japanese"],
      },
      {
        char: "🈲",
        name: "Japanese Prohibited Button",
        keywords: ["symbol", "japanese"],
      },
      { char: "🚼", name: "Baby Symbol", keywords: ["symbol", "baby"] },
      { char: "🅰️", name: "A Button", keywords: ["symbol", "letter"] },
      { char: "🅱️", name: "B Button", keywords: ["symbol", "letter"] },
      { char: "🆎", name: "AB Button", keywords: ["symbol", "letter"] },
      { char: "🆑", name: "CL Button", keywords: ["symbol", "letters"] },
      { char: "🅾️", name: "O Button", keywords: ["symbol", "letter"] },
      { char: "🆘", name: "SOS Button", keywords: ["symbol", "emergency"] },
      { char: "⛔", name: "No Entry", keywords: ["symbol", "stop"] },
      { char: "🛑", name: "Stop Sign", keywords: ["symbol", "stop"] },
      { char: "📛", name: "Name Badge", keywords: ["symbol", "sign"] },
      { char: "❌", name: "Cross Mark", keywords: ["symbol", "no"] },
      { char: "⭕", name: "Heavy Circle", keywords: ["symbol", "ok"] },
      { char: "🚫", name: "Prohibited", keywords: ["symbol", "stop"] },
      { char: "🔇", name: "Muted", keywords: ["symbol", "sound"] },
      { char: "🔕", name: "Bell with Slash", keywords: ["symbol", "sound"] },
      { char: "🚭", name: "No Smoking", keywords: ["symbol", "smoking"] },
      { char: "🚷", name: "No Pedestrians", keywords: ["symbol", "warning"] },
      { char: "🚯", name: "No Littering", keywords: ["symbol", "warning"] },
      { char: "🚳", name: "No Bicycles", keywords: ["symbol", "warning"] },
      {
        char: "🚱",
        name: "Non-Potable Water",
        keywords: ["symbol", "warning"],
      },
      { char: "🔞", name: "18+ Only", keywords: ["symbol", "age"] },
      { char: "📵", name: "No Mobile Phones", keywords: ["symbol", "warning"] },
      { char: "❗", name: "Exclamation Mark", keywords: ["symbol", "alert"] },
      {
        char: "❕",
        name: "White Exclamation Mark",
        keywords: ["symbol", "alert"],
      },
      { char: "❓", name: "Question Mark", keywords: ["symbol", "question"] },
      {
        char: "❔",
        name: "White Question Mark",
        keywords: ["symbol", "question"],
      },
      {
        char: "‼️",
        name: "Double Exclamation Mark",
        keywords: ["symbol", "alert"],
      },
      {
        char: "⁉️",
        name: "Exclamation Question Mark",
        keywords: ["symbol", "alert"],
      },
      { char: "💯", name: "100 Points", keywords: ["symbol", "score"] },
      { char: "🔅", name: "Dim Button", keywords: ["symbol", "light"] },
      { char: "🔆", name: "Bright Button", keywords: ["symbol", "light"] },
    ],
  },
];

export const PRECEPTION = [
  { id: "default", label: "Auto", mod: "" },
  { id: "1f3fb", label: "😀", mod: "\u{1F3FB}" },
  { id: "1f3fc", label: "👩", mod: "\u{1F3FC}" },
  { id: "1f3fd", label: "🎈", mod: "\u{1F3FD}" },
  { id: "1f3fe", label: "🍕", mod: "\u{1F3FE}" },
  { id: "1f3ff", label: "🚗", mod: "\u{1F3FF}" },
];

// Clean skin-tone injection
export function withType(char, toneMod) {
  if (!toneMod) return char;
  const baseChar = char.replace(/[\u{1F3FB}-\u{1F3FF}]/gu, "");
  return baseChar + toneMod;
}
